# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
all:
  javascripts:    [ frontend/njRoute.js, http://maps.google.com/maps/api/js?sensor=false, common/maps/maps.core.js, frontend/maps/maps.js ]