<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjNotificationSubscriber', 'doctrine');

/**
 * BaseNjNotificationSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nj_route_id
 * @property integer $user_id
 * @property NjNotification $NjNotification
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer                  getNjRouteId()      Returns the current record's "nj_route_id" value
 * @method integer                  getUserId()         Returns the current record's "user_id" value
 * @method NjNotification           getNjNotification() Returns the current record's "NjNotification" value
 * @method sfGuardUser              getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method NjNotificationSubscriber setNjRouteId()      Sets the current record's "nj_route_id" value
 * @method NjNotificationSubscriber setUserId()         Sets the current record's "user_id" value
 * @method NjNotificationSubscriber setNjNotification() Sets the current record's "NjNotification" value
 * @method NjNotificationSubscriber setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjNotificationSubscriber extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_notification_subscriber');
        $this->hasColumn('nj_route_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjNotification', array(
             'local' => 'nj_route_id',
             'foreign' => 'nj_route_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}