<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjStop', 'doctrine');

/**
 * BaseNjStop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property string $detail
 * @property decimal $latitude
 * @property decimal $longitude
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $NjStopTimes
 * @property Doctrine_Collection $NjRuns
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getDetail()      Returns the current record's "detail" value
 * @method decimal             getLatitude()    Returns the current record's "latitude" value
 * @method decimal             getLongitude()   Returns the current record's "longitude" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getNjStopTimes() Returns the current record's "NjStopTimes" collection
 * @method Doctrine_Collection getNjRuns()      Returns the current record's "NjRuns" collection
 * @method NjStop              setId()          Sets the current record's "id" value
 * @method NjStop              setDescription() Sets the current record's "description" value
 * @method NjStop              setDetail()      Sets the current record's "detail" value
 * @method NjStop              setLatitude()    Sets the current record's "latitude" value
 * @method NjStop              setLongitude()   Sets the current record's "longitude" value
 * @method NjStop              setCreatedAt()   Sets the current record's "created_at" value
 * @method NjStop              setUpdatedAt()   Sets the current record's "updated_at" value
 * @method NjStop              setNjStopTimes() Sets the current record's "NjStopTimes" collection
 * @method NjStop              setNjRuns()      Sets the current record's "NjRuns" collection
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjStop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_stop');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('latitude', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('longitude', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NjStopTime as NjStopTimes', array(
             'local' => 'id',
             'foreign' => 'nj_stop_id'));

        $this->hasMany('NjRun as NjRuns', array(
             'local' => 'id',
             'foreign' => 'nj_stop_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}