<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjVehicle', 'doctrine');

/**
 * BaseNjVehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nj_transport_mode_id
 * @property string $description
 * @property string $detail
 * @property NjTransportMode $NjTransportMode
 * @property NjTrip $NjTrips
 * 
 * @method integer         getId()                   Returns the current record's "id" value
 * @method integer         getNjTransportModeId()    Returns the current record's "nj_transport_mode_id" value
 * @method string          getDescription()          Returns the current record's "description" value
 * @method string          getDetail()               Returns the current record's "detail" value
 * @method NjTransportMode getNjTransportMode()      Returns the current record's "NjTransportMode" value
 * @method NjTrip          getNjTrips()              Returns the current record's "NjTrips" value
 * @method NjVehicle       setId()                   Sets the current record's "id" value
 * @method NjVehicle       setNjTransportModeId()    Sets the current record's "nj_transport_mode_id" value
 * @method NjVehicle       setDescription()          Sets the current record's "description" value
 * @method NjVehicle       setDetail()               Sets the current record's "detail" value
 * @method NjVehicle       setNjTransportMode()      Sets the current record's "NjTransportMode" value
 * @method NjVehicle       setNjTrips()              Sets the current record's "NjTrips" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjVehicle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_vehicle');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_transport_mode_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjTransportMode', array(
             'local' => 'nj_transport_mode_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('NjTrip as NjTrips', array(
             'local' => 'id',
             'foreign' => 'nj_vehicle_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}