<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjRun', 'doctrine');

/**
 * BaseNjRun
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nj_trip_id
 * @property integer $nj_stop_id
 * @property integer $step_into
 * @property integer $step_out
 * @property NjTrip $NjTrip
 * @property NjStop $NjStop
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getNjTripId()   Returns the current record's "nj_trip_id" value
 * @method integer getNjStopId()   Returns the current record's "nj_stop_id" value
 * @method integer getStepInto()   Returns the current record's "step_into" value
 * @method integer getStepOut()    Returns the current record's "step_out" value
 * @method NjTrip  getNjTrip()     Returns the current record's "NjTrip" value
 * @method NjStop  getNjStop()     Returns the current record's "NjStop" value
 * @method NjRun   setId()         Sets the current record's "id" value
 * @method NjRun   setNjTripId()   Sets the current record's "nj_trip_id" value
 * @method NjRun   setNjStopId()   Sets the current record's "nj_stop_id" value
 * @method NjRun   setStepInto()   Sets the current record's "step_into" value
 * @method NjRun   setStepOut()    Sets the current record's "step_out" value
 * @method NjRun   setNjTrip()     Sets the current record's "NjTrip" value
 * @method NjRun   setNjStop()     Sets the current record's "NjStop" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjRun extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_run');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_trip_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_stop_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('step_into', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('step_out', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjTrip', array(
             'local' => 'nj_trip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('NjStop', array(
             'local' => 'nj_stop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}