<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjTransportMode', 'doctrine');

/**
 * BaseNjTransportMode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property string $detail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property NjRoute $NjRoute
 * @property NjVehicle $NjVehicle
 * @property Doctrine_Collection $NjRoutes
 * @property Doctrine_Collection $NjVehicles
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getDetail()      Returns the current record's "detail" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method NjRoute             getNjRoute()     Returns the current record's "NjRoute" value
 * @method NjVehicle           getNjVehicle()   Returns the current record's "NjVehicle" value
 * @method Doctrine_Collection getNjRoutes()    Returns the current record's "NjRoutes" collection
 * @method Doctrine_Collection getNjVehicles()  Returns the current record's "NjVehicles" collection
 * @method NjTransportMode     setId()          Sets the current record's "id" value
 * @method NjTransportMode     setDescription() Sets the current record's "description" value
 * @method NjTransportMode     setDetail()      Sets the current record's "detail" value
 * @method NjTransportMode     setCreatedAt()   Sets the current record's "created_at" value
 * @method NjTransportMode     setUpdatedAt()   Sets the current record's "updated_at" value
 * @method NjTransportMode     setNjRoute()     Sets the current record's "NjRoute" value
 * @method NjTransportMode     setNjVehicle()   Sets the current record's "NjVehicle" value
 * @method NjTransportMode     setNjRoutes()    Sets the current record's "NjRoutes" collection
 * @method NjTransportMode     setNjVehicles()  Sets the current record's "NjVehicles" collection
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjTransportMode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_transport_mode');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjRoute', array(
             'local' => 'id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('NjVehicle', array(
             'local' => 'id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('NjRoute as NjRoutes', array(
             'local' => 'id',
             'foreign' => 'nj_transport_mode_id'));

        $this->hasMany('NjVehicle as NjVehicles', array(
             'local' => 'id',
             'foreign' => 'nj_transport_mode_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}