<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjEstimatedArrivalTime', 'doctrine');

/**
 * BaseNjEstimatedArrivalTime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nj_trip_id
 * @property integer $nj_stop_id
 * @property time $arrival_time
 * @property NjTrip $NjTrip
 * @property NjStop $NjStop
 * 
 * @method integer                getId()           Returns the current record's "id" value
 * @method integer                getNjTripId()     Returns the current record's "nj_trip_id" value
 * @method integer                getNjStopId()     Returns the current record's "nj_stop_id" value
 * @method time                   getArrivalTime()  Returns the current record's "arrival_time" value
 * @method NjTrip                 getNjTrip()       Returns the current record's "NjTrip" value
 * @method NjStop                 getNjStop()       Returns the current record's "NjStop" value
 * @method NjEstimatedArrivalTime setId()           Sets the current record's "id" value
 * @method NjEstimatedArrivalTime setNjTripId()     Sets the current record's "nj_trip_id" value
 * @method NjEstimatedArrivalTime setNjStopId()     Sets the current record's "nj_stop_id" value
 * @method NjEstimatedArrivalTime setArrivalTime()  Sets the current record's "arrival_time" value
 * @method NjEstimatedArrivalTime setNjTrip()       Sets the current record's "NjTrip" value
 * @method NjEstimatedArrivalTime setNjStop()       Sets the current record's "NjStop" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjEstimatedArrivalTime extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_estimated_arrival_time');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_trip_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_stop_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('arrival_time', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjTrip', array(
             'local' => 'nj_trip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('NjStop', array(
             'local' => 'nj_stop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}