<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjLoginGroupRouting', 'doctrine');

/**
 * BaseNjLoginGroupRouting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sf_guard_group_id
 * @property string $routing
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardGroup $sfGuardGroup
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getSfGuardGroupId()    Returns the current record's "sf_guard_group_id" value
 * @method string              getRouting()           Returns the current record's "routing" value
 * @method timestamp           getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()         Returns the current record's "updated_at" value
 * @method sfGuardGroup        getSfGuardGroup()      Returns the current record's "sfGuardGroup" value
 * @method NjLoginGroupRouting setId()                Sets the current record's "id" value
 * @method NjLoginGroupRouting setSfGuardGroupId()    Sets the current record's "sf_guard_group_id" value
 * @method NjLoginGroupRouting setRouting()           Sets the current record's "routing" value
 * @method NjLoginGroupRouting setCreatedAt()         Sets the current record's "created_at" value
 * @method NjLoginGroupRouting setUpdatedAt()         Sets the current record's "updated_at" value
 * @method NjLoginGroupRouting setSfGuardGroup()      Sets the current record's "sfGuardGroup" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjLoginGroupRouting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_login_group_routing');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('sf_guard_group_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('routing', 'string', 128, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup', array(
             'local' => 'sf_guard_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}