<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjStopTime', 'doctrine');

/**
 * BaseNjStopTime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nj_trip_id
 * @property integer $nj_stop_id
 * @property time $arrival_time
 * @property time $departure_time
 * @property integer $stop_sequence
 * @property string $description
 * @property string $detail
 * @property float $dist_traveled
 * @property NjTrip $NjTrip
 * @property NjStop $NjStop
 * @property Doctrine_Collection $NjNotifications
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getNjTripId()        Returns the current record's "nj_trip_id" value
 * @method integer             getNjStopId()        Returns the current record's "nj_stop_id" value
 * @method time                getArrivalTime()     Returns the current record's "arrival_time" value
 * @method time                getDepartureTime()   Returns the current record's "departure_time" value
 * @method integer             getStopSequence()    Returns the current record's "stop_sequence" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method string              getDetail()          Returns the current record's "detail" value
 * @method float               getDistTraveled()    Returns the current record's "dist_traveled" value
 * @method NjTrip              getNjTrip()          Returns the current record's "NjTrip" value
 * @method NjStop              getNjStop()          Returns the current record's "NjStop" value
 * @method Doctrine_Collection getNjNotifications() Returns the current record's "NjNotifications" collection
 * @method NjStopTime          setId()              Sets the current record's "id" value
 * @method NjStopTime          setNjTripId()        Sets the current record's "nj_trip_id" value
 * @method NjStopTime          setNjStopId()        Sets the current record's "nj_stop_id" value
 * @method NjStopTime          setArrivalTime()     Sets the current record's "arrival_time" value
 * @method NjStopTime          setDepartureTime()   Sets the current record's "departure_time" value
 * @method NjStopTime          setStopSequence()    Sets the current record's "stop_sequence" value
 * @method NjStopTime          setDescription()     Sets the current record's "description" value
 * @method NjStopTime          setDetail()          Sets the current record's "detail" value
 * @method NjStopTime          setDistTraveled()    Sets the current record's "dist_traveled" value
 * @method NjStopTime          setNjTrip()          Sets the current record's "NjTrip" value
 * @method NjStopTime          setNjStop()          Sets the current record's "NjStop" value
 * @method NjStopTime          setNjNotifications() Sets the current record's "NjNotifications" collection
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjStopTime extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_stop_time');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_trip_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_stop_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('arrival_time', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('departure_time', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('stop_sequence', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('dist_traveled', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjTrip', array(
             'local' => 'nj_trip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('NjStop', array(
             'local' => 'nj_stop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('NjNotification as NjNotifications', array(
             'local' => 'id',
             'foreign' => 'nj_stop_time_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}