<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjSectionRouting', 'doctrine');

/**
 * BaseNjSectionRouting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $menu_order
 * @property string $description
 * @property string $detail
 * @property string $routing
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property NjMenuItemRouting $NjMenuItemRouting
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method integer           getMenuOrder()         Returns the current record's "menu_order" value
 * @method string            getDescription()       Returns the current record's "description" value
 * @method string            getDetail()            Returns the current record's "detail" value
 * @method string            getRouting()           Returns the current record's "routing" value
 * @method timestamp         getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp         getUpdatedAt()         Returns the current record's "updated_at" value
 * @method NjMenuItemRouting getNjMenuItemRouting() Returns the current record's "NjMenuItemRouting" value
 * @method NjSectionRouting  setId()                Sets the current record's "id" value
 * @method NjSectionRouting  setMenuOrder()         Sets the current record's "menu_order" value
 * @method NjSectionRouting  setDescription()       Sets the current record's "description" value
 * @method NjSectionRouting  setDetail()            Sets the current record's "detail" value
 * @method NjSectionRouting  setRouting()           Sets the current record's "routing" value
 * @method NjSectionRouting  setCreatedAt()         Sets the current record's "created_at" value
 * @method NjSectionRouting  setUpdatedAt()         Sets the current record's "updated_at" value
 * @method NjSectionRouting  setNjMenuItemRouting() Sets the current record's "NjMenuItemRouting" value
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjSectionRouting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_section_routing');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('menu_order', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('routing', 'string', 128, array(
             'type' => 'string',
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjMenuItemRouting', array(
             'local' => 'id',
             'foreign' => 'nj_section_routing_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}