<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NjRoute', 'doctrine');

/**
 * BaseNjRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nj_transport_mode_id
 * @property string $number
 * @property string $name
 * @property string $description
 * @property string $detail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property NjTransportMode $NjTransportMode
 * @property Doctrine_Collection $NjTrips
 * @property Doctrine_Collection $NjNotifications
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getNjTransportModeId()    Returns the current record's "nj_transport_mode_id" value
 * @method string              getNumber()               Returns the current record's "number" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method string              getDetail()               Returns the current record's "detail" value
 * @method timestamp           getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()            Returns the current record's "updated_at" value
 * @method NjTransportMode     getNjTransportMode()      Returns the current record's "NjTransportMode" value
 * @method Doctrine_Collection getNjTrips()              Returns the current record's "NjTrips" collection
 * @method Doctrine_Collection getNjNotifications()      Returns the current record's "NjNotifications" collection
 * @method NjRoute             setId()                   Sets the current record's "id" value
 * @method NjRoute             setNjTransportModeId()    Sets the current record's "nj_transport_mode_id" value
 * @method NjRoute             setNumber()               Sets the current record's "number" value
 * @method NjRoute             setName()                 Sets the current record's "name" value
 * @method NjRoute             setDescription()          Sets the current record's "description" value
 * @method NjRoute             setDetail()               Sets the current record's "detail" value
 * @method NjRoute             setCreatedAt()            Sets the current record's "created_at" value
 * @method NjRoute             setUpdatedAt()            Sets the current record's "updated_at" value
 * @method NjRoute             setNjTransportMode()      Sets the current record's "NjTransportMode" value
 * @method NjRoute             setNjTrips()              Sets the current record's "NjTrips" collection
 * @method NjRoute             setNjNotifications()      Sets the current record's "NjNotifications" collection
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo            <jfrizo@gmail.com>;
               Rafael Mardegan       <mardegan.rafael@gmail.com>;
               Yohan Araújo          <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNjRoute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nj_route');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nj_transport_mode_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('number', 'string', 50, array(
             'type' => 'string',
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 128,
             ));
        $this->hasColumn('detail', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NjTransportMode', array(
             'local' => 'nj_transport_mode_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('NjTrip as NjTrips', array(
             'local' => 'id',
             'foreign' => 'nj_route_id'));

        $this->hasMany('NjNotification as NjNotifications', array(
             'local' => 'id',
             'foreign' => 'nj_route_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}