generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NjNotification
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              Notification
    plural:                Notifications
    route_prefix:          nj_notification
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Notification List
        display:  [=id, njNotificationType, njTrip, njStopTime, created_at, updated_at]

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
