<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/05 03:53:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=graviola',
  'username' => 'graviola',
  'password' => 'graviola',
  'name' => 'doctrine',
)),);
