<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/07 21:11:03
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
