<?php
// auto-generated by sfViewConfigHandler
// date: 2011/12/05 17:46:45
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }


  $response->addStylesheet('blueprint/liquidScreen.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('frontend.css', '', array ());
  $response->addJavascript('jquery.min.js', '', array ());
  $response->addJavascript('menu.js', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=false', '', array ());
  $response->addJavascript('common/maps/maps.core.js', '', array ());
  $response->addJavascript('frontend/maps/maps.js', '', array ());


