<?php

/**
 * NjCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjCalendar');
    }
    
    public function getSchedule($route_id, $calendar_id) {
        $query = $this->createQuery('c')
                      ->select('r.id')
                      ->addSelect('c.description')
                      ->addSelect('t.direction_id')
                      ->addSelect('s.departure_time')
                      ->innerJoin('c.NjTrips t')
                      ->innerJoin('t.NjRoute r')
                      ->innerJoin('t.NjStopTimes s')
                      ->where('s.stop_sequence = 0')
                      ->andWhere('r.id = ?', array($route_id))
                      ->andWhere('c.id = ?', array($calendar_id))
                      ->orderBy('c.description')
                      ->addOrderBy('s.departure_time');
        return $query->fetchArray();
    }

}