<?php

/**
 * NjEstimatedArrivalTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjEstimatedArrivalTimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjEstimatedArrivalTimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjEstimatedArrivalTime');
    }
    
    /**
     * Returns an NjEstimatedArrivelTime of a given NjTrip and NjStop
     * 
     * @return object NjStopTimeTable
     */
    public function getNjEstimatedArrivalTime($trip_id, $stop_id)
    {
        return $this->createQuery('est')
            ->where('est.nj_trip_id = ?', $trip_id)
            ->andWhere('est.nj_stop_id = ?', $stop_id)
            ->fetchOne();
    }

}