<?php

/**
 * NjLoginGroupRoutingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjLoginGroupRoutingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjLoginGroupRoutingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjLoginGroupRouting');
    }

    /**
     * Get routing url based on a given group
     * @param String $group Group Name
     * @return array Relation of routing of the given group.
     */
    public function getRoutingByGroup($group)
    {
      $query = $this->createQuery('n')
                    ->innerJoin('n.sfGuardGroup s')
                    ->where('s.name = ?', $group);
      return $query->fetchArray();
    }
}