<?php

/**
 * NjMenuItemRoutingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjMenuItemRoutingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjMenuItemRoutingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjMenuItemRouting');
    }
}