<?php

/**
 * NjNotificationTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjNotificationTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjNotificationTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjNotificationType');
    }
}