<?php

/**
 * NjNotificationSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjNotificationSubscriberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjNotificationSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjNotificationSubscriber');
    }
    
    public static function isSubscriber($user_id, $route_id) 
    {
       $q = NjNotificationSubscriberTable::getInstance()->createQuery('ns')
               ->where('user_id ='.$user_id)
               ->andWhere('nj_route_id ='.$route_id);
       $result = $q->execute();
       
       if($result->count() > 0)
           $result = true;
       else
           $result = false;

       return $result;
    }
    
     public static function getNjNotificationSubscriber($user_id, $route_id) 
    {
       $q = NjNotificationSubscriberTable::getInstance()->createQuery('ns')
               ->where('user_id', array($user_id))
               ->addWhere('nj_route_id', array($route_id));
       
       return $q->fetchOne();
    }

}