<?php

/**
 * NjNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjNotification');
    }
    
    public static function getRoutesNotifications($routes) 
    {
        $q = NjNotificationTable::getInstance()->createQuery('not')
                  ->whereIn('nj_route_id', $routes)
                  ->orWhere('nj_route_id = null')
                  ->orderBy('created_at');
        
        return $q->execute();
    }
    
    public static function getRoutesNotificationsForSubscriber($user_id)
    {
      $q = NjNotificationTable::getInstance()->createQuery('not')
                ->innerJoin('not.NjNotificationSubscriber sub ON not.nj_route_id = sub.nj_route_id')
                ->innerJoin('sub.sfGuardUser use ON use.id = sub.user_id')
                ->where('user_id ='.$user_id);
      
        return $q->execute();
    }
     public static function getSubscribedNotifications() 
    {
         //TODO resolver!
        $q = NjNotificationTable::getInstance()->createQuery('not')
                 ->where('(nj_route_id = null AND nj_trip_id = null AND nj_stop_time_id = null) OR (nj_route_id = nj_route_id)')
                 ->orderBy('created_at');
        
        return $q->execute();
    }
}