<?php

/**
 * NjRouteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjRouteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjRouteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjRoute');
    }
    
    public function loadTransportsFromRoute($route_id) {
        $query = $this->createQuery()
                      ->select('n.id AS nj_vehicle_id,
                                n.number AS nj_number,
                                n2.id AS nj_route_id,
                                n3.id AS nj_vehicle_type_id,
                                n3.description nj_vehicle_type')
                      ->from('NjVehicle n')
                      ->innerJoin('n.NjRoute n2')
                      ->innerJoin('n.NjVehicleType n3')
                      ->where('n.nj_route_id = ?', $route_id);
        return $query->fetchArray();
    }    
}