<?php

/**
 * NjSectionRoutingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjSectionRoutingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjSectionRoutingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjSectionRouting');
    }
}