<?php

/**
 * NjStopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjStopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjStopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjStop');
    }
    
    
    /**
     * Returns NjStops for given NjRoute
     * 
     * @return object NjTripTable
     */
    public function getStopsFromRoute($route)
    {
       $q = Doctrine_Query::create()
              ->select('s.description')
               ->addSelect('s.latitude')
               ->addSelect('s.longitude')
              ->from('NjStop s')
              ->where('s.nj_route_id = ?', $route);

      return $q->execute();
    }

}