<?php

/**
 * NjTransportModeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjTransportModeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjTransportModeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjTransportMode');
    }
}