<?php

/**
 * NjTripTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjTripTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjTripTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjTrip');
    }
}