<?php

/**
 * NjTypeNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjTypeNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjTypeNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjTypeNotification');
    }
}