<?php

/**
 * NjUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NjUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NjUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NjUserProfile');
    }
}