# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    charset: utf-8
    
    standard_helpers: [Partial, Cache, I18N]
    
    # Form security secret (CSRF protection)
    csrf_secret:            92a1b6f69b96f4af22c7bbb4425009b10a2f38b9

    #i18n
    #TODO change to pt_BR
    i18n: true
    default_culture: en

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Enable modules
    enabled_modules:        [ default, sfGuardAuth, sfGuardRegister, sfGuardForgotPassword  ]

    login_module:           sfGuardAuth
    login_action:           secure

    secure_module:          sfGuardAuth
    secure_action:          secure
