<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/13 03:31:16
sfConfig::add(array(
  'mod_njdatasimulation_enabled' => true,
  'mod_njdatasimulation_view_class' => 'sfPHP',
));
