<?php
// auto-generated by sfViewConfigHandler
// date: 2011/12/11 18:34:33
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('blueprint/liquidScreen.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('backend.css', '', array ());
  $response->addJavascript('/sfAdminThemejRollerPlugin/js/jquery.min.js', '', array ());
  $response->addJavascript('menu.js', '', array ());


