<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/10 19:53:53
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'AdminNotifications',
  ),
);
