<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/11 21:39:53
sfConfig::add(array(
  'mod_njdatasimulation_enabled' => true,
  'mod_njdatasimulation_view_class' => 'sfPHP',
));
