<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/07 19:39:57
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'AccessFrontend',
  ),
);
