<?php
// auto-generated by sfViewConfigHandler
// date: 2011/12/11 21:40:08
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'jsonSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('blueprint/liquidScreen.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('backend.css', '', array ());
  $response->addJavascript('/sfAdminThemejRollerPlugin/js/jquery.min.js', '', array ());
  $response->addJavascript('menu.js', '', array ());
  $response->addJavascript('https://www.google.com/jsapi?autoload={"modules":[{"name":"visualization", "version":"1", "packages":["charteditor"]}]}', '', array ());
  $response->addJavascript('common/graphs/graphs.core.js', '', array ());
  $response->addJavascript('backend/graphs/graphs.js', '', array ());
}
else if ($templateName.$this->viewName == 'jsonSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('blueprint/liquidScreen.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('backend.css', '', array ());
  $response->addJavascript('/sfAdminThemejRollerPlugin/js/jquery.min.js', '', array ());
  $response->addJavascript('menu.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('blueprint/liquidScreen.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('backend.css', '', array ());
  $response->addJavascript('/sfAdminThemejRollerPlugin/js/jquery.min.js', '', array ());
  $response->addJavascript('menu.js', '', array ());
}

