<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/11 18:34:33
sfConfig::add(array(
  'mod_njnotification_enabled' => true,
  'mod_njnotification_view_class' => 'sfPHP',
));
