<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/10 19:41:21
sfConfig::add(array(
  'mod_njnotification_enabled' => true,
  'mod_njnotification_view_class' => 'sfPHP',
));
