<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/07 19:39:54
$this->security = array (
  'termandconditions' => 
  array (
    'is_secure' => false,
  ),
  'privacystatement' => 
  array (
    'is_secure' => false,
  ),
  'advertise' => 
  array (
    'is_secure' => false,
  ),
  'about' => 
  array (
    'is_secure' => false,
  ),
  'contact' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'AccessBackend',
  ),
);
