showSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njTripView]

editSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njTrip]

newSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njTrip]

AddStopSuccess:
  has_layout: false