<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroup');
    }

    /**
     * Get all permissions by a given group.
     */
    public function getPermissionsByGroup($group)
    {
      $query = $this->createQuery('s')
                    ->select('s.id, s2.group_id, s3.id, s3.name')
                    ->innerJoin('s.sfGuardGroupPermission s2')
                    ->innerJoin('s2.Permission s3')
                    ->where('s.name = ?', $group);
      return $query->fetchArray();
    }
}