<?php

/**
 * sfGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    graviola
 * @subpackage model
 * @author     Felipe Vieira         <nvieirafelipe@gmail.com>;
               Jean Frizo       <jfrizo@gmail.com>;
               Rafael Mardegan  <mardegan.rafael@gmail.com>;
               Yohan AraÃºjo     <yohanaraujo07@gmail.com>;
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardGroupPermission extends PluginsfGuardGroupPermission
{

}