showSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njStop]

editSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njStop]

newSuccess:
  javascripts:    [http://maps.google.com/maps/api/js?sensor=false&libraries=geometry, common/maps/maps.core.js, backend/njStop]
  
RouteJsonSuccess:
  has_layout: false  