<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/10 18:26:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=tunnel.pagodabox.com;dbname=graviola-db',
  'username' => 'lourie',
  'password' => 'uKPizMpg',
  'name' => 'doctrine',
)),);
