<?php

/**
 * ArticleAuthor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    projectWithDoctrine
 * @subpackage model
 * @author     Christian Kerl
 * @version    SVN: $Id: ArticleAuthor.class.php 26442 2010-01-10 00:21:58Z chrisk $
 *
 * @PropertyStrategy('ckDoctrinePropertyStrategy')
 */
class ArticleAuthor extends BaseArticleAuthor
{

}