<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/05 03:48:04
sfConfig::add(array(
  'app_sf_admin_theme_jroller_plugin_web_dir' => '/sfAdminThemejRollerPlugin',
  'app_sf_admin_theme_jroller_plugin_use_jquery' => true,
  'app_sf_admin_theme_jroller_plugin_theme_dir' => '/sfAdminThemejRollerPlugin/css/jquery',
  'app_sf_admin_theme_jroller_plugin_theme' => 'redmond',
  'app_sf_admin_theme_jroller_plugin_theme_switcher' => false,
  'app_sf_admin_theme_jroller_plugin_css_reset' => true,
  'app_sf_admin_theme_jroller_plugin_list_actions_position' => 'left',
  'app_sf_admin_theme_jroller_plugin_edit_tab_position' => 'vertical',
  'app_sf_admin_theme_jroller_plugin_icons' => array (
  'new' => 'plus',
  'filter' => 'check',
  'filters' => 'search',
  'reset' => 'circle-close',
  'show' => 'document',
  'edit' => 'pencil',
  'delete' => 'trash',
  'list' => 'arrowreturnthick-1-w',
  'save' => 'circle-check',
  'saveAndAdd' => 'circle-plus',
  'first' => 'seek-first',
  'previous' => 'seek-prev',
  'next' => 'seek-next',
  'last' => 'seek-end',
),
  'app_enable_soap_parameter' => 'off',
  'app_sf_guard_plugin_remember_cookie_name' => 'graviolaRememberMe',
));
